---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Install docker
      block:
        - name: Adding universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Install addition packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - lsb-release
              - gnupg
              - curl
            update-cache: yes
            cache_valid_time: 86400

        - name: Adding docker key
          # Можно сделать командойб но не желательно
          # command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Installing stable repository
          apt_repository:
            repo: >
              deb [ arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
              https://download.docker.com/linux/ubuntu 
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: yes
            filename: docker

        - name: Install docker-ce
          apt:
            name: docker-ce
            update-cache: yes
            cache_valid_time: 86400

        - name: Checking if docker installed and rebooted
          service:
            name: docker
            state: restarted
            enabled: yes
      become: yes

    - name: Install docker-compose
      block:
        - name: Getting latest version of docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Installing docker-compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: yes

    - name: Finish installing
      block:
        - name: Adding user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

        - name: Reboot server
          reboot:
      become: yes
