---
- name: user
  hosts: demo
  vars:
    state0: present
    user: aynur
  tasks:
    - name: Preconfig block
      block:
        - name: Sleep
          command: /bin/sleep 15
          async: 1000
          poll: 0
          register: sleep

        - debug:
            var: sleep

        - name: Echo
          command: echo "AYNUR, I'M DONE!!!"

    - name: Check sleep status
      async_status:
        jid: "{{ sleep.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 1
