---
- name: "[{{ name }}] config configuration"
  block:
    - name: "[{{ name }}] config creating"
      vars:
        config_file: "{{ lookup('template', '{{ config_item }}.j2') }}"
      community.docker.docker_config:
        name: "{{ config_item }}"
        data: "{{ config_file | b64encode }}"
        labels:
          config: "{{ config_file | hash('sha1') }}"
        data_is_b64: true
        state: present
      loop:
        - nginx.conf
      loop_control:
        loop_var: config_item
      tags: "{{ name }}"
  rescue:
    - name: "[{{ name }}] deleting service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent
    - name: "[{{ name }}] config creating"
      vars:
        config_file: "{{ lookup('template', '{{ config_item }}.j2') }}"
      community.docker.docker_config:
        name: "{{ config_item }}"
        data: "{{ config_file | b64encode }}"
        labels:
          config: "{{ config_file | hash('sha1') }}"
        data_is_b64: true
        state: present
      loop:
        - nginx.conf
      loop_control:
        loop_var: config_item
      tags: "{{ name }}"

- name: "[{{ name }}] service  deploy"
  block:
    - name: "[{{ name }}] secret deploy"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "nginx:{{ version }}"
        state: present
        force_update: true
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
        configs:
          - config_name: nginx.conf
            filename: "/etc/nginx/nginx.conf"
  tags: "{{ name }}"
