galaxy_info:
  role_name: preconfig
  description: Configuring server to work with docker
  author: Aynur Shauerman
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - all
  dependencies:
    - role: deploy
