---
- name: "[{{ name }}] secret configuration"
  include: "../secret.yml"

- name: "[{{ name }}] service  deploy"
  block:
    - name: "[{{ name }}] secret deploy"
      community.dodcker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
  tags: "{{ name }}"
