---
- name: "[{{ name }}] config configuration"
  block:
    - name: "[{{ name }}] config creating"
      vars:
        env_file: "{{ lookup('template', '{{ name }}/{{ config_item }}.j2') }}"
      community.docker.docker_config:
        name: "{{ config_item }}"
        data: "{{ config_file | b64encode }}"
        labels:
          config: "{{ config_file | hash('sha1') }}"
        data_is_b64: true
        state: present
  tags: "{{ name }}"
  rescue:
    - name: "[{{ name }}] deleting service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent
    - name: "[{{ name }}] config creating"
      vars:
        env_file: "{{ lookup('template', '{{ name }}/{{ config_item }}.j2') }}"
      community.docker.docker_config:
        name: "{{ config_item }}"
        data: "{{ config_file | b64encode }}"
        labels:
          config: "{{ config_file | hash('sha1') }}"
        data_is_b64: true
        state: present
