---
- name: "[{{ name }}] secret creating"
  vars:
    envFile: "{{ lookup('file', '.env.j2') }}"
  community.dodcker.docker_secret:
    name: "{{ name }}/.env"
    data: "{{ envFile | b64encode }}"
    label:
      secret: "{{ envFile | hash('sha1') }}"
    data_is_b64: true
    state: present
