---
- name: "[{{ name }}] secret configuration"
  block:
    - name: "[{{ name }}] secret creating"
      include: "secret-create.yml"
  rescue:
    - name: "[{{ name }}] deleting service"
      community.dodcker.docker_swarm_service:
        name: "{{ name }}"
        state: absent
    - name: "[{{ name }}] secret creating"
      include: "secret-create.yml"
