---
- name: "[{{ name }}] secret creating"
  vars:
    env_file: "{{ lookup('file', '.env.j2') }}"
  community.dodcker.docker_secret:
    name: "{{ name }}/.env"
    data: "{{ env_file | b64encode }}"
    label:
      secret: "{{ env_file | hash('sha1') }}"
    data_is_b64: true
    state: present
