---
- name: "[{{ name }}] secret configuration"
  block:
    - name: "[{{ name }}] secret creating"
      include_tasks: "secret-create.yml"
  rescue:
    - name: "[{{ name }}] deleting service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent
    - name: "[{{ name }}] secret creating"
      include_tasks: "secret-create.yml"
