galaxy_info:
  role_name: swarm_init
  description: Initialization of swarm cluster
  author: Aynur Shauerman
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - all
