---
# - name: Installing Docker
#   block:
#     - name: Adding universe
#       yum_repository:
#         name: "epel"
#         description: "EPEL YUM repo"
#         baseurl: https://download.docker.com/linux/centos/docker-ce.repo
#         state: present

#     - name: Install additional packages
#       yum:
#         name:
#           - yum-utils
#         update_cache: yes

#     - name: Install docker-ce
#       yum:
#         name:
#           - docker-ce
#           - docker-ce-cli
#           - containerd.io
#           - docker-compose-plugin
#         update_cache: yes

#     - name: Check if docker installed and reboot
#       service:
#         name: docker
#         state: restarted
#         enabled: yes
#   become: true

# - name: Installing docker-compose
#   block:
#     - name: Getting last version of docker-compose
#       uri:
#         url: https://api.github.com/repos/docker/compose/releases/latest
#         body_format: json
#         timeout: 90
#       register: page

#     - name: Installing docker-compose
#       get_url:
#         url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
#         dest: /usr/local/bin/docker-compose
#         mode: 0755
#   become: true

- name: End of instalation
  block:
    # - name: Adding user to the docker group
    #   user:
    #     name: "{{ ansible_user }}"
    #     group: docker

    - name: Reboot server
      reboot:
        test_command: pwd
  become: true
